---
title: "Exploratory Data Analysis"
output: pdf_document
---

# Introduction
This document presents an exploratory data analysis of the dataset.

## Dependency Setup
```{r Dependency Setup, inlcude = TRUE}

if (!require("here")) install.packages("here")
library(here)

# Set current working directory to file location
setwd(here::here())

#Print current working directory in case not connected to .Rproj file
print(getwd())

# Define the path to the .renv lockfile within the 'renv' folder
renv_lockfile <- file.path(getwd(), "renv.lock")

# Activate and restore packages from renv lock file
if (!require("renv")) install.packages("renv")
renv::restore()

# Use the p_load function to install and load any desired packages that may not 
# have been in the renv.lock file. Note, if the packages were already in the 
# renv.lock file, that is okay. `p_load` will not change version number

if (!require("pacman")) install.packages("pacman")
pacman::p_load(renv, rmarkdown,  knitr, tidyverse, reshape2, haven, xtable
               gridExtra, broom, car, caret, Metrics)

# Update the renv lock file
renv::snapshot()
```

# Data Loading
```{r}

# Load custom functions
source("custom_functions.R")

# load data
wave1 <- read_dta("~/Desktop/DataSci/DATA2020-Spring2024/DATA2020_Final_Project/data/raw/FF_wave1_2020v2.dta")
wave2 <- read_dta("~/Desktop/DataSci/DATA2020-Spring2024/DATA2020_Final_Project/data/raw/FF_wave2_2020v2.dta")
wave3 <- read_dta("~/Desktop/DataSci/DATA2020-Spring2024/DATA2020_Final_Project/data/raw/FF_wave3_2020v2.dta")
wave4 <- read_dta("~/Desktop/DataSci/DATA2020-Spring2024/DATA2020_Final_Project/data/raw/FF_wave4_2020v2.dta")
wave5 <- read_dta("~/Desktop/DataSci/DATA2020-Spring2024/DATA2020_Final_Project/data/raw/FF_wave5_2020v2.dta")
wave6 <- read_dta("~/Desktop/DataSci/DATA2020-Spring2024/DATA2020_Final_Project/data/raw/FF_wave6_2020v2.dta")
```

# Summary Statistics
```{r}
# Code to summarize the data




```

# Data Visualization
```{r}
# Code for data visualization






```
